//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UInvcapcao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYRAPCHIEUPHIMEntities : DbContext
    {
        public QUANLYRAPCHIEUPHIMEntities()
            : base("name=QUANLYRAPCHIEUPHIMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblGhePhongChieu> tblGhePhongChieux { get; set; }
        public virtual DbSet<tblGioChieu> tblGioChieux { get; set; }
        public virtual DbSet<tblLichChieu> tblLichChieux { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanViens { get; set; }
        public virtual DbSet<tblPhim> tblPhims { get; set; }
        public virtual DbSet<tblPhongChieu> tblPhongChieux { get; set; }
        public virtual DbSet<tblQuyenTruyCap> tblQuyenTruyCaps { get; set; }
        public virtual DbSet<tblRap> tblRaps { get; set; }
        public virtual DbSet<tblTheLoai> tblTheLoais { get; set; }
        public virtual DbSet<tblVe> tblVes { get; set; }
    }
}
