//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UInvcapcao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGhePhongChieu
    {
        public string MaGhe { get; set; }
        public string MaRap { get; set; }
        public string MaPhong { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual tblPhongChieu tblPhongChieu { get; set; }
        public virtual tblRap tblRap { get; set; }
        public virtual tblVe tblVe { get; set; }
    }
}
