//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UInvcapcao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKhach
    {
        public string MaKhach { get; set; }
        public string MatKhauKhach { get; set; }
        public int MaLoai { get; set; }
    
        public virtual tblLoaiKhach tblLoaiKhach { get; set; }
    }
}
