//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UInvcapcao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLichChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLichChieu()
        {
            this.tblVes = new HashSet<tblVe>();
        }
    
        public string MaShow { get; set; }
        public string MaPhim { get; set; }
        public string MaRap { get; set; }
        public string MaPhong { get; set; }
        public Nullable<System.DateTime> NgayChieu { get; set; }
        public string MaGioChieu { get; set; }
        public Nullable<int> GiaVe { get; set; }
        public Nullable<int> SoVeDaBan { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        public virtual tblGioChieu tblGioChieu { get; set; }
        public virtual tblPhim tblPhim { get; set; }
        public virtual tblPhongChieu tblPhongChieu { get; set; }
        public virtual tblRap tblRap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVe> tblVes { get; set; }
    }
}
