//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UInvcapcao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhanVien()
        {
            this.tblQuyenHans = new HashSet<tblQuyenHan>();
        }
    
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public string MatKhauNV { get; set; }
        public string ChucVu { get; set; }
        public Nullable<int> Luong { get; set; }
        public string MaRap { get; set; }
    
        public virtual tblRap tblRap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuyenHan> tblQuyenHans { get; set; }
    }
}
