//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UInvcapcao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPhim()
        {
            this.tblLichChieux = new HashSet<tblLichChieu>();
        }
    
        public string MaPhim { get; set; }
        public string TenPhim { get; set; }
        public string MaTheLoai { get; set; }
        public Nullable<System.DateTime> NgayKhoiChieu { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> TongChiPhi { get; set; }
        public Nullable<int> TongThu { get; set; }
        public string TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLichChieu> tblLichChieux { get; set; }
        public virtual tblTheLoai tblTheLoai { get; set; }
    }
}
