//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UInvcapcao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhongChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPhongChieu()
        {
            this.tblGhePhongChieux = new HashSet<tblGhePhongChieu>();
            this.tblLichChieux = new HashSet<tblLichChieu>();
        }
    
        public string MaPhong { get; set; }
        public string MaRap { get; set; }
        public string TenPhong { get; set; }
        public Nullable<int> TongSoGhe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGhePhongChieu> tblGhePhongChieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLichChieu> tblLichChieux { get; set; }
        public virtual tblRap tblRap { get; set; }
    }
}
