//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UInvcapcao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuyenTruyCap
    {
        public Nullable<int> MaQuyenTruyCap { get; set; }
        public string TenQuyenTruyCap { get; set; }
        public string MaNV { get; set; }
    
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
