//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UInvcapcao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuyenHan
    {
        public int MaQuyen { get; set; }
        public string MaNV { get; set; }
        public int MaChucNang { get; set; }
    
        public virtual tblChucNang tblChucNang { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
