//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UInvcapcao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThongTinVe
    {
        public int IdTTVe { get; set; }
        public Nullable<int> MaVe { get; set; }
        public string MaGhe { get; set; }
        public string TenPhim { get; set; }
        public Nullable<System.DateTime> NgayChieu { get; set; }
        public string GioChieu { get; set; }
        public Nullable<int> GiaVe { get; set; }
        public string HinhThucThanhToan { get; set; }
        public string MaShow { get; set; }
        public string PhongChieu { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual tblGhePhongChieu tblGhePhongChieu { get; set; }
        public virtual tblVe tblVe { get; set; }
    }
}
