//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UInvcapcao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVe
    {
        public string MaGhe { get; set; }
        public string MaShow { get; set; }
    
        public virtual tblGhePhongChieu tblGhePhongChieu { get; set; }
        public virtual tblLichChieu tblLichChieu { get; set; }
    }
}
